language: go

go:
  - 1.7

sudo: false

git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="source"

install:
  - go get -u -v github.com/spf13/hugo

script:
  - hugo
